### ISSUE TITLE
Representing users

### ISSUE THREAD

**Issue by pwalsh** [openspending/os-style-guide#1]
# Description

We need patterns for representing users. This means 2 things:
1. A small widget for the menu bar with avatar/name, etc., and a drop down to "see profile"
2. A modal box that shows a "card for the user" (example: something like when looking at someone in the directory in Slack)

On point 2, I specifically say a modal box because many "apps" for OpenSpending will be simple client side affairs, and we would not want to have to implement special routes etc. for profile pages. Also profiles will be **read only** as the user's data is just populated for us from the Auth provider we use (Google OAuth at this stage). 
# Tasks
- [x] Design for a widget
  - [x] Login/Signup when user is not authed (both are the same action in OAuth flow)
  - [x] Name + avatar with drop down when user is authed
  - [x] In drop down, two actions: "Profile" (pops the modal) and "Logout"
- [x] Design for a "Profile card" (what should we call this?)
  - Avatar
  - First Name
  - Last Name
  - OpenSpending user since {DATE}
  - {x} packages on OpenSpending

**Comment by smth** [comment]
I started making this as a modal variant, but the disconnect from the link wasn't making sense to me. I have now made it as a variation on the dropdown. See the second [header](http://labs.openspending.org/os-style-guide/).

**Comment by pwalsh** [comment]
@smth excellent solution.
